.TH mbtg 1 "2011 march 21"

.SH NAME
MBTG - Memory Based Tagger generator
.SH SYNOPSYS
mbtg -T <filename> -s <setting filename>

or

mbtg [options]

.SH DESCRIPTION

This programs generates, based on a tagged corpus, all the files needed to be able to tag a text with 
.B mbt.
.

.SH OPTIONS

.BR -h " or " --help
.RS
show help
.RE


.BR -T " <tagged training corpus file>"

or

.BR -E " <enriched tagged training corpus file>"

All further options have reasonable defaults, so using them is only
needed for the experienced user. See the mbt manual for more details.

.BR -s " settingsfile"
.RS
.B mbtg
creates this file, which can be used to run 
.B mbt
with minimal effort. (like mbt -s settings -T somefile)
.RE

.BR -p " pattern"
.RS
the pattern for known words (default ddfa)
.RE

.BR -P " pattern"
.RS
the pattern for unknown words (default dFapsss)
.RE

.BR -% " <number>"
.RS
filter threshold for ambitag construction (default 5%)
.RE

.BR -l " <lexiconfile>"

.BR -L " <file with list of frequent words>"

.BR -r " <ambitagfile>"

.BR -k " <known words case base>"

.BR -u " <unknown words case base>"

.BR -K " <known words instances file>"

.BR -U " <unknown words instances file>"

.BR -V " or " --version
.RS
show version info
.RE

.BR -e " <sentence delimiter> (default '<utt>')"

.B -X
.RS
keep the intermediate files
.RE

.BR -O "timbl options"
.RS
 (Note: there is NO SPACE between O and the options)
  <options>   classifier options for both known and unknown words instances bases
  K: <options>   classifier options for known words instance base
  U: <options>   classifier options for unknown words case base
  valid 
.B timbl
options are: a d k m q v w x -
.RE

.SH BUGS
possibly

.SH AUTHORS
Ko van der Sloot Timbl@uvt.nl

Antal van den Bosch Timbl@uvt.nl

.SH SEE ALSO
.BR timbl (1)
.BR mbt (1)
.BR mbtserver (1)
